import { GenderTypeEnum } from '@shared';
import { IRProductDetailRoot } from './app/core/interface/response/product.response';

export const dummyDataGenderMenu = {
  data: [
    {
      gender: GenderTypeEnum.Men,
      collections: [
        {
          id: 1,
          name: 'Casual Wear',
          description: 'Comfortable everyday wear for men.',
          categories: [
            { id: 1, name: 'T-Shirts', description: 'Cotton and polo tees' },
            { id: 2, name: 'Jeans', description: 'Slim and regular fit denim' },
          ],
        },
        {
          id: 5,
          name: 'Formal Collection',
          description: 'Office-ready formals for men.',
          categories: [
            { id: 9, name: 'Shirts', description: 'Plain and striped shirts' },
            { id: 10, name: 'Trousers', description: 'Classic formal trousers' },
          ],
        },
        {
          id: 8,
          name: 'Footwear',
          description: 'Stylish shoes for every occasion.',
          categories: [
            { id: 15, name: 'Sneakers', description: 'Casual sneakers' },
            { id: 16, name: 'Formal Shoes', description: 'Leather office shoes' },
          ],
        },
        {
          id: 10,
          name: 'New Arrivals',
          description: 'Latest trending styles.',
          categories: [
            { id: 19, name: 'Graphic Tees', description: 'Trendy printed t-shirts' },
            { id: 20, name: 'Joggers', description: 'Casual comfy joggers' },
          ],
        },
      ],
    },
    {
      gender: GenderTypeEnum.Women,
      collections: [
        {
          id: 2,
          name: 'Ethnic Collection',
          description: 'Traditional and festive styles.',
          categories: [
            { id: 3, name: 'Sarees', description: 'Designer silk sarees' },
            { id: 4, name: 'Kurtis', description: 'Cotton and printed kurtis' },
          ],
        },
        {
          id: 6,
          name: 'Western Wear',
          description: 'Trendy modern outfits.',
          categories: [
            { id: 11, name: 'Dresses', description: 'Casual and party wear' },
            { id: 12, name: 'Tops', description: 'Stylish tops and blouses' },
          ],
        },
        {
          id: 9,
          name: 'Accessories',
          description: 'Complete your outfit with these.',
          categories: [
            { id: 17, name: 'Bags', description: 'Handbags and clutches' },
            { id: 18, name: 'Jewellery', description: 'Earrings and necklaces' },
          ],
        },
      ],
    },
    {
      gender: GenderTypeEnum.Both,
      collections: [
        {
          id: 4,
          name: 'Activewear',
          description: 'Fitness and sports collection.',
          categories: [
            { id: 7, name: 'Track Pants', description: 'Quick-dry fabric' },
            { id: 8, name: 'Hoodies', description: 'Winter workout wear' },
          ],
        },
        {
          id: 7,
          name: 'Winter Collection',
          description: 'Warm and cozy clothes for kids.',
          categories: [
            { id: 13, name: 'Sweaters', description: 'Woolen pullovers' },
            { id: 14, name: 'Jackets', description: 'Windproof jackets' },
          ],
        },
      ],
    },
  ],
};

export const wishlistArray = {
  data: [
    {
      id: 1,
      name: 'Luxe Matka Silk Anarkali',
      isCustomSize: false,
      customSizeName: '',
      color: ['Red', 'Maroon'],
      mrp: 78465.9,
      gender: 'Women',
      productURL: ['assets/images/wishlist-1.png', 'assets/images/wishlist-2.png'],
      isActive: true,
      stockId: 101,
      size: 'M',
      quantity: 1,
      icon: 'assets/icons/delete-black.svg',
    },
    {
      id: 2,
      name: 'Elegant Cotton Saree',
      isCustomSize: false,
      customSizeName: '',
      color: ['Blue', 'White'],
      mrp: 12345.0,
      gender: 'Women',
      productURL: ['assets/images/wishlist-2.png', 'assets/images/wishlist-3.png'],
      isActive: true,
      stockId: 102,
      size: 'L',
      quantity: 1,
      icon: 'assets/icons/delete-black.svg',
    },
    {
      id: 3,
      name: 'Chic Designer Lehenga',
      isCustomSize: true,
      customSizeName: 'Custom Fit',
      color: ['Pink', 'Gold'],
      mrp: 54321.5,
      gender: 'Women',
      productURL: ['assets/images/wishlist-3.png', 'assets/images/wishlist-1.png'],
      isActive: true,
      stockId: 103,
      size: '',
      quantity: 1,
      icon: 'assets/icons/delete-black.svg',
    },
    {
      id: 4,
      name: 'Classic Georgette Dress',
      isCustomSize: false,
      customSizeName: '',
      color: ['Green'],
      mrp: 26789.99,
      gender: 'Women',
      productURL: ['assets/images/wishlist-4.png', 'assets/images/wishlist-5.png'],
      isActive: true,
      stockId: 104,
      size: 'S',
      quantity: 1,
      icon: 'assets/icons/delete-black.svg',
    },
    {
      id: 5,
      name: 'Stylish Silk Kurti',
      isCustomSize: false,
      customSizeName: '',
      color: ['Purple'],
      mrp: 19876.75,
      gender: 'Women',
      productURL: ['assets/images/wishlist-2.png', 'assets/images/wishlist-5.png'],
      isActive: true,
      stockId: 105,
      size: 'M',
      quantity: 1,
      icon: 'assets/icons/delete-black.svg',
    },
  ],
};

export const dynamicCatalogData = {
  total: 7,
  filter: {
    category: [
      { id: 1, name: 'Saree', count: 7, isSelected: false },
      { id: 2, name: 'Embroidered Saree', count: 2, isSelected: false },
    ],
    color: [
      { id: 1, name: '#FF0000', count: 2, isSelected: false },
      { id: 2, name: '#000000', count: 3, isSelected: false },
      { id: 3, name: '#0000FF', count: 1, isSelected: false },
      { id: 4, name: '#FFC0CB', count: 1, isSelected: false },
    ],
    size: [{ id: 1, name: 'Free Size', count: 7 }],
    minPrice: 20000,
    maxPrice: 28000,
  },
  products: [
    {
      id: 1,
      name: 'Red Madras Muse Saree',
      color: ['Red'],
      sizes: ['Free Size'],
      mrp: 28000,
      gender: 'Women',
      isWishList: false,
      productURL: ['assets/images/saree-1.png'],
    },
    {
      id: 2,
      name: 'Never Not Iconic Saree',
      color: ['Black'],
      sizes: ['Free Size'],
      mrp: 28000,
      gender: 'Women',
      isWishList: false,
      productURL: ['assets/images/saree-2.png'],
    },
    {
      id: 3,
      name: 'Black Palm Theory Saree',
      color: ['Black'],
      sizes: ['Free Size'],
      mrp: 20000,
      gender: 'Women',
      isWishList: true,
      productURL: ['assets/images/saree-3.png'],
    },
    {
      id: 4,
      name: 'Black Heath Phool Saree',
      color: ['Black'],
      sizes: ['Free Size'],
      mrp: 24000,
      gender: 'Women',
      isWishList: true,
      productURL: ['assets/images/wishlist-1.png'],
    },
    {
      id: 5,
      name: 'Red Madras Muse Saree',
      color: ['Red'],
      sizes: ['Free Size'],
      mrp: 28000,
      gender: 'Women',
      isWishList: false,
      productURL: ['assets/images/saree-5.png'],
    },
    {
      id: 6,
      name: 'Never Not Iconic Saree',
      color: ['Black'],
      sizes: ['Free Size'],
      mrp: 28000,
      gender: 'Women',
      isWishList: false,
      productURL: ['assets/images/saree-6.png'],
    },
    {
      id: 7,
      name: 'Black Palm Theory Saree',
      color: ['Black'],
      sizes: ['Free Size'],
      mrp: 20000,
      gender: 'Women',
      isWishList: false,
      productURL: ['assets/images/saree-7.png'],
    },
  ],
};

export const dummyProductDetail: IRProductDetailRoot = {
  id: 101,
  name: "Men's Casual Cotton Shirt",
  categoryIds: [1, 4],
  isCustomSize: false,
  customSizeName: '',
  color: ['Blue', 'White', 'Black'],
  mrp: 1999,
  gender: 'Men',
  productURL: [
    'assets/images/mens-wear-1.png',
    'assets/images/mens-wear-2.png',
    'assets/images/mens-wear-3.png',
    'assets/images/mens-wear-4.png',
  ],
  activeImage: 'assets/images/mens-wear-1.png',
  isActive: true,
  variants: [
    {
      id: 1,
      productId: 101,
      name: 'Slim Fit - Blue',
      description: 'Soft cotton fabric with a modern slim fit design.',
      mrp: 1999,
      variantURL: 'assets/images/mens-wear-1.png',
      stocks: [
        { id: 1, productId: 101, variantId: 1, quantity: 25, reservedQuantity: 2, size: 'S' },
        { id: 2, productId: 101, variantId: 1, quantity: 30, reservedQuantity: 3, size: 'M' },
        { id: 3, productId: 101, variantId: 1, quantity: 20, reservedQuantity: 1, size: 'L' },
      ],
    },
    {
      id: 2,
      productId: 101,
      name: 'Regular Fit - White',
      description: 'Breathable cotton shirt with classic regular fit.',
      mrp: 1799,
      variantURL: 'assets/images/mens-wear-2.png',
      stocks: [
        { id: 4, productId: 101, variantId: 2, quantity: 15, reservedQuantity: 1, size: 'S' },
        { id: 5, productId: 101, variantId: 2, quantity: 25, reservedQuantity: 2, size: 'M' },
        { id: 6, productId: 101, variantId: 2, quantity: 18, reservedQuantity: 1, size: 'L' },
      ],
    },
  ],
  stocks: [
    { id: 11, productId: 101, variantId: 1, quantity: 25, reservedQuantity: 2, size: 'S' },
    { id: 12, productId: 101, variantId: 1, quantity: 30, reservedQuantity: 3, size: 'M' },
    { id: 13, productId: 101, variantId: 2, quantity: 15, reservedQuantity: 1, size: 'S' },
    { id: 14, productId: 101, variantId: 2, quantity: 25, reservedQuantity: 2, size: 'M' },
  ],
  descriptions: [
    {
      id: 1,
      productId: 101,
      header: 'Material & Care',
      descriptionType: 'Details',
      description: '100% cotton. Machine wash cold. Do not bleach. Warm iron if needed.',
      shortDescription: 'Comfortable cotton fabric suitable for daily wear.',
      jsonText: []
    },
    {
      id: 2,
      productId: 101,
      header: 'Fit & Style',
      descriptionType: 'Style',
      description: 'Available in slim and regular fits with button-down collars.',
      shortDescription: 'Perfect for casual or semi-formal outings.',
      jsonText: []
    },
  ],
};
